4MM013<br>
Python Assessment 2<br>
Description<br>
This assessment will allow you to demonstrate your Python programming abilities by producing
solutions to the following questions. For each question you will need to produce evidence of the code
you have created, ideally in an IDE, and also proof of the valid output generated by running your
code. The code created should also satisfy the following requirements;<br>
● Use suitable variable and function names which, where possible, betray the data type or function’s
operation / role.<br>
● Use comments to explain the primary operations, role, or behaviour of your code.<br>
● Contain a “##” title with a description, your name and student number at the start of the program.<br>
The total marks for the assessment is 15.<br>
4MM013 Python Assessment 02<br>
2022/23 Sem 2<br>
Wolverhampton University<br>
Question 1<br>
(5 marks)<br>
Create a python script that will prompt the user for 9 values, checking that they are all valid numbers,
and populate those given values into a 3x3 Matrix called A.
The program should present the created matrix , the determinant of the matrix and, if possible, the
inverse of the matrix.
The program should also present the results of the matrix operations A*A and A*A*A.<br>
Finally the program should print the number of values in the matrix that >= 10
You will need to evidence the outputs, as well as the error handling of any invalid values when the
user attempts to input them in the matrix.

In [6]:
import numpy as np

def prompt_user_for_matrix_values(matrix_size):
    """
    Prompts the user for values to populate a matrix of a given size.
    
    Args:
    - matrix_size: a tuple representing the size of the matrix as (num_rows, num_columns)
    
    Returns:
    - A numpy array representing the matrix created from user input
    """
    matrix = np.zeros(matrix_size)
    for i in range(matrix_size[0]):
        for j in range(matrix_size[1]):
            while True:
                try:
                    value = float(input(f"Enter a value for row {i+1}, column {j+1}: "))
                    break
                except ValueError:
                    print("Invalid input. Please enter a valid number.")
            matrix[i][j] = value
    return matrix

def print_matrix_info(matrix):
    """
    Prints information about a matrix including the matrix itself, its determinant, its inverse (if possible), the result of
    A*A and A*A*A, and the number of values in the matrix that are >= 10.
    
    Args:
    - matrix: a numpy array representing the matrix to be analyzed
    """
    print(f"Matrix:\n{matrix}")
    determinant = np.linalg.det(matrix)
    print(f"Determinant: {determinant}")
    if determinant != 0:
        inverse = np.linalg.inv(matrix)
        print(f"Inverse:\n{inverse}")
    else:
        print("Matrix is not invertible.")
    A_squared = np.matmul(matrix, matrix)
    A_cubed = np.matmul(A_squared, matrix)
    print(f"A*A:\n{A_squared}\nA*A*A:\n{A_cubed}")
    count = np.sum(matrix >= 10)
    print(f"Number of values in matrix that are >= 10: {count}")

# prompt the user for a 3x3 matrix
A = prompt_user_for_matrix_values((3,3))

# analyze the matrix
print_matrix_info(A)



Enter a value for row 1, column 1: 1
Enter a value for row 1, column 2: 2
Enter a value for row 1, column 3: 3
Enter a value for row 2, column 1: 4
Enter a value for row 2, column 2: 5
Enter a value for row 2, column 3: 6
Enter a value for row 3, column 1: 7
Enter a value for row 3, column 2: 8
Enter a value for row 3, column 3: 9
Matrix:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Determinant: 0.0
Matrix is not invertible.
A*A:
[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]
A*A*A:
[[ 468.  576.  684.]
 [1062. 1305. 1548.]
 [1656. 2034. 2412.]]
Number of values in matrix that are >= 10: 0


Question 2<br>
(5 marks)<br>
Write and test a Python function, that makes use of numpy, to return the sum of the elements on the
main diagonal (upper left to lower right) of a square matrix. In linear algebra, this value is called the
trace of the matrix.<br>
For example, with a matrix represented as a list of lists eg. [[9, 8, 7], [6, 5, 4], [3, 2, 1]], your function
should return (9 + 5 + 1) = “15”.
Your Python function solution should work for any sized square matrix passed to it.<br> Demonstrate
that this is the case with 3x3, 4x4, and 6x6 matrix examples.


In [8]:
def trace(matrix):

  return np.trace(matrix)

# creating 3x3 matrix
matrix_3x3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(trace(matrix_3x3))

# creating 4x4 matrix
matrix_4x4 = np.array([[3,5,7,9],[2,4,6,8],[1,2,3,4],[9,8,7,6]])
print(trace(matrix_4x4))
# creating 6x6 matric
matrix_6x6 = np.array([[10,11,12,13,14,15],[16,17,18,19,20,21],[22,23,24,25,26,27],[28,29,30,31,32,33],[34,35,36,37,38,39]])
print(trace(matrix_6x6))

15
16
120


Question 3<br>
(5 marks)<br>
Ackermann's function (A) is defined as:
A(m,n):<br>
n+1, if m=0<br>
A(m-1,1), if m>0 and n=0<br>
A(m-1,A(m,n-1)), if m>0 and n> 0<br>
Write a recursive Python function to implement Ackermann's function. How many recursive calls will
be required to evaluate A(2,3)?



In [9]:
def Ackermann(m,n):
  if m == 0:
    return n+1
  elif n==0:
    return Ackermann(m-1,10)
  else:
    return Ackermann(m-1,Ackermann(m,n-1))
print(Ackermann(2,3))

54
